### PR TITLE
Added CNAME

### PR DESCRIPTION
**Pull request by leonkunert**

### CODE REVIEW

**Comment by fenhl** [comment]
> The page build completed successfully, but returned the following warning: 
> 
> CNAME already taken: hematite.piston.rs 
> 
> For information on troubleshooting Jekyll see: 
> 
> https://help.github.com/articles/using-jekyll-with-pages#troubleshooting 
> 
> If you have any questions you can contact us by replying to this email.

**Comment by leonkunert** [comment]
That was my fork. I deleted my repo. We should be good now.

**Comment by fenhl** [comment]
Can we force-rebuild the page?

**Comment by leonkunert** [comment]
The sites are rebuild on every commit. I don't know of any manual way to force it apart from that.

**Comment by fenhl** [comment]
I guess we'll just wait for the next commit then.

**Pull request merged**
